livery = {
	{"VSN_EF_Textur4",	DIFFUSE			,	"vsn_ef_textur4", false};
	{"VSN_EF_Textur4",	NORMAL_MAP			,	"vsn_ef_textur4_b", false};
	{"VSN_EF_Landing_Light",	DIFFUSE			,	"vsn_ef_landing-light.tga", false};
	{"VSN_EF_glass",	DIFFUSE			,	"vsn_ef_glass", false};
	{"VSN_EF_glass",	SPECULAR			,	"vsn_ef_glass_s", false};
	{"VSN_EF_Textur2_Wing_L",	DIFFUSE			,	"vsn_ef_textur2_wing_l", false};
	{"VSN_EF_Textur2_Wing_L",	NORMAL_MAP			,	"vsn_ef_textur2_wing_l_b", false};
	{"VSN_EF_Textur6",	DIFFUSE			,	"vsn_ef_textur6", false};
	{"VSN_EF_Textur6",	NORMAL_MAP			,	"vsn_ef_textur6_b", false};
	{"VSN_EF_Helmet",	DIFFUSE			,	"ef_helmet", false};
	{"VSN_F35C_Pilot",	DIFFUSE			,	"vsn_f35a_pilot", false};
	{"VSN_F35C_Pilot",	NORMAL_MAP			,	"vsn_f35c_pilot_b", false};
	{"Material #183",	DIFFUSE			,	"antena - copia", false};
	{"Material #185",	DIFFUSE			,	"helmet_tube", false};
	{"Material #185",	12,	"scenes", false};
	{"VSN_EF_Pilot",	DIFFUSE			,	"vsn_ef_pilot-diffuse", false};
	{"VSN_EF_Textur5",	DIFFUSE			,	"vsn_ef_textur5", false};
	{"VSN_EF_Textur5",	NORMAL_MAP			,	"vsn_ef_textur5_b", false};
	{"VSN_EF_Hud",	DIFFUSE			,	"vsn_ef_hud", false};
	{"VSN_EF_Textur1",	DIFFUSE			,	"vsn_ef_textur1", false};
	{"VSN_EF_Textur1",	NORMAL_MAP			,	"vsn_ef_textur1_b", false};
	{"VSN_EF_Textur3",	DIFFUSE			,	"vsn_ef_textur3", false};
	{"VSN_EF_Textur3",	NORMAL_MAP			,	"vsn_ef_textur3_b", false};
	{"VSN_EF_LightsOn",	DIFFUSE			,	"vsn_ef_lightson", false};
	{"VSN_EF_LightsOff",	DIFFUSE			,	"vsn_ef_lightsoff", false};
	{"VSN_EF_Textur2_Wing_R",	DIFFUSE			,	"vsn_ef_textur2_wing_r", false};
	{"VSN_EF_Textur2_Wing_R",	NORMAL_MAP			,	"vsn_ef_textur2_wing_r_b", false};
	{"VSN_EF_POD_R",	DIFFUSE			,	"vsn_ef_wing_pod_r_t", false};
	{"VSN_EF_Green",	DIFFUSE			,	"vsn_ef_bano-green.tga", false};
	{"Material #194",	DIFFUSE			,	"tail_l", false};
	{"VSN_EF_Textur2_Wing_R",	DIFFUSE			,	"vsn_ef_textur2_wing_r", false};
	{"VSN_EF_Textur2_Wing_R",	NORMAL_MAP			,	"vsn_ef_textur2_wing_r_b", false};
	{"VSN_EF_Textur2_Wing_L",	DIFFUSE			,	"vsn_ef_textur2_wing_l", false};
	{"VSN_EF_Textur2_Wing_L",	NORMAL_MAP			,	"vsn_ef_textur2_wing_l_b", false};
	{"VSN_EF_POD_L",	DIFFUSE			,	"vsn_ef_wing_pod_l_t ", false};
	{"VSN_EF_Red",	DIFFUSE			,	"vsn_ef_bano-red.tga", false};
	{"VSN_EF_white",	DIFFUSE			,	"vsn_ef_bano-white.tga", false};
	{"VSN_EF_Tankstutzen",	DIFFUSE			,	"vsn_ef_tankstutzen", false};
	{"VSN_EF_Tankstutzen",	NORMAL_MAP			,	"vsn_ef_tankstutzen_b", false};
	{"Material #3",	DIFFUSE			,	"tail_l", false};
	{"Material #3",	11,	"tail_l_spec", false};
	{"Material #1793",	DIFFUSE			,	"vsn_engineering_details", false};
	{"Material #1791",	DIFFUSE			,	"vsn_engineering_details", false};
	{"Material #1794",	DIFFUSE			,	"vsn_engineering_details", false};
	{"Material #1792",	DIFFUSE			,	"vsn_engineering_details", false};
	{"Material #1796",	DIFFUSE			,	"scnmcgnp_2k_albedo", false};
	{"Material #1796",	NORMAL_MAP			,	"scnmcgnp_2k_normal", false};
	{"Material #1796",	SPECULAR			,	"scnmcgnp_2k_metalness", false};
	{"Material #1797",	DIFFUSE			,	"ef_mach", false};
	{"Material #1798",	DIFFUSE			,	"cloudnew2", false};
	{"_01_-_Default1",	DIFFUSE			,	"tail_r", false};
	{"_01_-_Default1",	12,	"tail_r_spec", false};
}
